### ISSUE TITLE
Unix only?

### ISSUE THREAD

**Issue by jasonelaw** [Ironholds/olctools#3]
Is the package really Unix only? Browsing the source, I see the NEWS file mentions a removed dependency on BOOST, but the [NEWS](https://github.com/Ironholds/olctools/blob/7d1f54aca27fee7faf5dd590ed737b8de8b3ca52/DESCRIPTION) file still has a unix only flag.

**Comment by Ironholds** [comment]
Good point; forgot to remove it. Thanks!
