### ISSUE TITLE
Bug in OLC short code recovery

### ISSUE THREAD

**Issue by drinckes** [Ironholds/olctools#5]
Hi - we recently discovered a bug in the recover or recoverNearest algorithm for Open Location Code. We've fixed it in the libraries in the main github project. To see what changes we made, you can refer to [this issue](https://github.com/google/open-location-code/issues/37), and it's linked pull request, for details on how you can make the fix in your own code.

Thanks for using OLC!

**Comment by Ironholds** [comment]
Thanks!

**Comment by Ironholds** [comment]
Hmn. Well, I made the change and it's still producing  796RXF22+. That's...strange :|

**Comment by drinckes** [comment]
I think you've fixed it. The CRAN library (0.2.1) does this (sadness):

```
> shorten_olc("796RXG22+", 14.95125,-23.5001)
[1] "22+"
> recover_olc("22+", 14.95125,-23.5001)
[1] "65GG3222+"
```

When I install using  devtools::install_github("ironholds/olctools") I get (happiness):

```
> shorten_olc("796RXG22+", 14.95125,-23.5001)
[1] "22+"
> recover_olc("22+", 14.95125,-23.5001)
[1] "796RXG22+"
```

I'd suggest adding two test cases to the test_shortener.R code:

```
expect_equal(recover_olc("22+", 42.899, 9.012), "8FJFW222+")
expect_equal(recover_olc("22+", 14.95125 -23.5001), "796RXG22+")
```

**Comment by Ironholds** [comment]
Hmn - okay, that's super weird. Ah well! Good calls on the regression tests, too. I'll push this out overnight to CRAN, bundled with the NA support!
